fix: remove getOutput because its breaking downstream leading to type conflicts;
example
```
lib/solvers/PortPointPathingSolver/hgportpointpathingsolver/HgPortPointPathingSolverClass.ts(757,3): error TS2416: Property 'getOutput' in type 'HgPortPointPathingSolver' is not assignable to the same property in base type 'HyperGraphSolver<RegionHg, RegionPortHg, Candidate<RegionHg, RegionPortHg>>'.
  Type '() => { nodesWithPortPoints: NodeWithPortPoints[]; inputNodeWithPortPoints: InputNodeWithPortPoints[]; }' is not assignable to type '() => SolvedRoute[]'.
    Type '{ nodesWithPortPoints: NodeWithPortPoints[]; inputNodeWithPortPoints: InputNodeWithPortPoints[]; }' is missing the following properties from type 'SolvedRoute[]': length, pop, push, concat, and 35 more.
```
 which is not ideal